language: node_js
node_js:
  - "0.10"
  - "0.11"
  - "0.8"
  - "0.6"
before_install: npm install -g grunt-cli
install: npm install
matrix:
  fast_finish: true
  allow_failures:
  - node_js: "0.11"
  - node_js: "0.8"
  - node_js: "0.6"