# appveyor file
# http://www.appveyor.com/docs/appveyor-yml

init:
  - git config --global core.autocrlf input

environment:
  matrix:
    - nodejs_version: 0.10
    - nodejs_version: 0.11
    - nodejs_version: 0.8

matrix:
  allow_failures:
    - nodejs_version: 0.11
    - nodejs_version: 0.8

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g grunt-cli
  - npm install
  - npm uninstall grunt

test_script:
  - node --version
  - npm --version
  - ps: grunt --no-color  # PowerShell
  - cmd: grunt --no-color

build: off